name: dbt_voter_project
version: 1.0.0
config-version: 2
profile: voter_duckdb
model-paths: ["models"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_voter_project:
    +materialized: view
