voter_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '../airflow/include/data/processed/goodparty.duckdb') }}"
      schema: main
      threads: 4
      extensions: []
