{% macro standardize_state(column_name) %}
    case
        when {{ column_name }} is null or trim({{ column_name }}) = '' then null
        else case
            when upper(trim({{ column_name }})) in ('ALABAMA', 'AL') then 'AL'
            when upper(trim({{ column_name }})) in ('ALASKA', 'AK') then 'AK'
            when upper(trim({{ column_name }})) in ('ARIZONA', 'AZ') then 'AZ'
            when upper(trim({{ column_name }})) in ('ARKANSAS', 'AR') then 'AR'
            when upper(trim({{ column_name }})) in ('CALIFORNIA', 'CA') then 'CA'
            when upper(trim({{ column_name }})) in ('COLORADO', 'CO') then 'CO'
            when upper(trim({{ column_name }})) in ('CONNECTICUT', 'CT') then 'CT'
            when upper(trim({{ column_name }})) in ('DELAWARE', 'DE') then 'DE'
            when upper(trim({{ column_name }})) in ('FLORIDA', 'FL') then 'FL'
            when upper(trim({{ column_name }})) in ('GEORGIA', 'GA') then 'GA'
            when upper(trim({{ column_name }})) in ('HAWAII', 'HI') then 'HI'
            when upper(trim({{ column_name }})) in ('IDAHO', 'ID') then 'ID'
            when upper(trim({{ column_name }})) in ('ILLINOIS', 'IL') then 'IL'
            when upper(trim({{ column_name }})) in ('INDIANA', 'IN') then 'IN'
            when upper(trim({{ column_name }})) in ('IOWA', 'IA') then 'IA'
            when upper(trim({{ column_name }})) in ('KANSAS', 'KS') then 'KS'
            when upper(trim({{ column_name }})) in ('KENTUCKY', 'KY') then 'KY'
            when upper(trim({{ column_name }})) in ('LOUISIANA', 'LA') then 'LA'
            when upper(trim({{ column_name }})) in ('MAINE', 'ME') then 'ME'
            when upper(trim({{ column_name }})) in ('MARYLAND', 'MD') then 'MD'
            when upper(trim({{ column_name }})) in ('MASSACHUSETTS', 'MA') then 'MA'
            when upper(trim({{ column_name }})) in ('MICHIGAN', 'MI') then 'MI'
            when upper(trim({{ column_name }})) in ('MINNESOTA', 'MN') then 'MN'
            when upper(trim({{ column_name }})) in ('MISSISSIPPI', 'MS') then 'MS'
            when upper(trim({{ column_name }})) in ('MISSOURI', 'MO') then 'MO'
            when upper(trim({{ column_name }})) in ('MONTANA', 'MT') then 'MT'
            when upper(trim({{ column_name }})) in ('NEBRASKA', 'NE') then 'NE'
            when upper(trim({{ column_name }})) in ('NEVADA', 'NV') then 'NV'
            when upper(trim({{ column_name }})) in ('NEW HAMPSHIRE', 'NH') then 'NH'
            when upper(trim({{ column_name }})) in ('NEW JERSEY', 'NJ') then 'NJ'
            when upper(trim({{ column_name }})) in ('NEW MEXICO', 'NM') then 'NM'
            when upper(trim({{ column_name }})) in ('NEW YORK', 'NY') then 'NY'
            when upper(trim({{ column_name }})) in ('NORTH CAROLINA', 'NC') then 'NC'
            when upper(trim({{ column_name }})) in ('NORTH DAKOTA', 'ND') then 'ND'
            when upper(trim({{ column_name }})) in ('OHIO', 'OH') then 'OH'
            when upper(trim({{ column_name }})) in ('OKLAHOMA', 'OK') then 'OK'
            when upper(trim({{ column_name }})) in ('OREGON', 'OR') then 'OR'
            when upper(trim({{ column_name }})) in ('PENNSYLVANIA', 'PA') then 'PA'
            when upper(trim({{ column_name }})) in ('RHODE ISLAND', 'RI') then 'RI'
            when upper(trim({{ column_name }})) in ('SOUTH CAROLINA', 'SC') then 'SC'
            when upper(trim({{ column_name }})) in ('SOUTH DAKOTA', 'SD') then 'SD'
            when upper(trim({{ column_name }})) in ('TENNESSEE', 'TN') then 'TN'
            when upper(trim({{ column_name }})) in ('TEXAS', 'TX') then 'TX'
            when upper(trim({{ column_name }})) in ('UTAH', 'UT') then 'UT'
            when upper(trim({{ column_name }})) in ('VERMONT', 'VT') then 'VT'
            when upper(trim({{ column_name }})) in ('VIRGINIA', 'VA') then 'VA'
            when upper(trim({{ column_name }})) in ('WASHINGTON', 'WA') then 'WA'
            when upper(trim({{ column_name }})) in ('WEST VIRGINIA', 'WV') then 'WV'
            when upper(trim({{ column_name }})) in ('WISCONSIN', 'WI') then 'WI'
            when upper(trim({{ column_name }})) in ('WYOMING', 'WY') then 'WY'
            when upper(trim({{ column_name }})) in ('DISTRICT OF COLUMBIA', 'WASHINGTON DC', 'WASHINGTON, DC', 'DC') then 'DC'
            else null
        end
    end
{% endmacro %}
